package com.py.sifenpy.client.ruc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-10-21T21:11:42.497-03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", name = "de-ws-consultas-consulta-ruc")
@XmlSeeAlso({ObjectFactory.class})
public interface DeWsConsultasConsultaRuc {

    @WebMethod
    @RequestWrapper(localName = "rEnviConsRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "com.py.sifenpy.client.ruc.REnviConsRUC")
    @ResponseWrapper(localName = "rResEnviConsRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "com.py.sifenpy.client.ruc.RResEnviConsRUC")
    public void rEnviConsRUC(

        @WebParam(name = "dId", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        java.math.BigInteger dId,
        @WebParam(name = "dRUCCons", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        java.lang.String dRUCCons,
        @WebParam(mode = WebParam.Mode.OUT, name = "dCodRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        jakarta.xml.ws.Holder<java.lang.String> dCodRes,
        @WebParam(mode = WebParam.Mode.OUT, name = "dMsgRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        jakarta.xml.ws.Holder<java.lang.String> dMsgRes,
        @WebParam(mode = WebParam.Mode.OUT, name = "xContRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        jakarta.xml.ws.Holder<TContenedorRuc> xContRUC
    );
}
