package com.py.sifenpy.client.ruc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-10-21T20:13:38.291-03:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "de-ws-consultas-consulta-rucService",
                  wsdlLocation = "file:/home/ignacio/app-java/blog/sifenpy/src/main/resources/wsdl/consulta-ruc.wsdl",
                  targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
public class DeWsConsultasConsultaRucService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-consultas-consulta-rucService");
    public static final QName DeWsConsultasConsultaRucSoap12 = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-consultas-consulta-rucSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ignacio/app-java/blog/sifenpy/src/main/resources/wsdl/consulta-ruc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeWsConsultasConsultaRucService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/ignacio/app-java/blog/sifenpy/src/main/resources/wsdl/consulta-ruc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeWsConsultasConsultaRucService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeWsConsultasConsultaRucService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeWsConsultasConsultaRuc
     */
    @WebEndpoint(name = "de-ws-consultas-consulta-rucSoap12")
    public DeWsConsultasConsultaRuc getDeWsConsultasConsultaRucSoap12() {
        return super.getPort(DeWsConsultasConsultaRucSoap12, DeWsConsultasConsultaRuc.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeWsConsultasConsultaRuc
     */
    @WebEndpoint(name = "de-ws-consultas-consulta-rucSoap12")
    public DeWsConsultasConsultaRuc getDeWsConsultasConsultaRucSoap12(WebServiceFeature... features) {
        return super.getPort(DeWsConsultasConsultaRucSoap12, DeWsConsultasConsultaRuc.class, features);
    }

}
